In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import scipy.io as sio
from PIL import Image
from eightpoint import eightpoint
from epipolarCorrespondence import epipolarCorrespondence
from essentialMatrix import essentialMatrix
from camera2 import camera2
from triangulate import triangulate
from displayEpipolarF import displayEpipolarF
from epipolarMatchGUI import epipolarMatchGUI

In [2]:
img1 = cv2.imread('../data/im1.png')
img2 = cv2.imread('../data/im2.png')
pts = np.load('../data/someCorresp.npy', allow_pickle=True).tolist()

In [3]:
pts1 = pts['pts1']      #(x,y) coordinate in piture 1
pts2 = pts['pts2']      #(x,y) coordinate in piture 2
M = pts['M']            #scalar parameter

# write your code here
R1, t1 = np.eye(3), np.zeros((3, 1))
R2, t2 = np.eye(3), np.zeros((3, 1))


In [4]:
F = eightpoint(pts1, pts2, M)

In [5]:
pts1.shape

(110, 2)

In [6]:
F = eightpoint(pts1, pts2, M)

In [7]:
print(F)

[[-1.66208174e+09  2.12258319e+10 -1.58972178e+09]
 [-2.07291848e+10  1.67027408e+09  3.78082829e+09]
 [ 2.06226421e+09 -4.38052674e+09  2.07360000e+06]]


In [8]:
M

1440.0